# -*- coding: utf-8 -*-
"""modulo1 aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g9Igc6GDSnAy7V86W_clXUfjDgjBFwoc

# Aula 1!
introdução
"""

idade = 23

numero = 3

"""soma"""

resultado = idade + numero

resultado

"""subtração"""

idade - numero

"""multiplicação"""

dobro = idade * 2

idade * 2 + 3

idade * (2 + 3)

"""divisão"""

metade = idade / 2

"""potência"""

numero ** 2

"""raiz quadrada"""

numero ** (1/2)

24 **(0.5)

"""listas"""

l = [1, 2, 3, 4]

l

l[3]

l[-1]

l[0:3]

#l[3] +3
l[3] + l[3]

"""string"""

nome = "antonio"

print(nome)

nome[0:4]

apelido = nome[0:4]

apelido.lower()

apelido.upper()

nome.lower()

nome.upper()

"""dicionario"""

precos = {'Biscoitos': 4.99, 'Suco':2.48}

precos

precos['Biscoitos']

precos['Suco']

precos['Biscoitos'] * 5

round(precos['Biscoitos'] * 5,4)

"""operadores relacionais"""

precos

precos['Biscoitos'] < precos['Suco']

precos['Biscoitos'] == 3

precos['Biscoitos'] == 4.99

precos['Biscoitos'] >= 5

precos['Biscoitos'] != precos['Suco']

precos['Biscoitos'] == precos['Suco']

nome

apelido

nome == apelido